# Based on JDK 11, as I think that is the most recent version which works with FTB Omnia and I'm assuming that more recent versions of Java have better optimizations
FROM openjdk:8-jre
LABEL maintainer="matthew+docker@wolfie.ovh"
# Upgrade all packages to latest versions available
RUN apt-get update
RUN apt-get upgrade -y
# Make sure we have jq for JSON parsing
RUN apt-get install jq -y

# Create install directory if it isn't mounted to the host already
RUN mkdir -p cd /opt/minecraftftb

WORKDIR /tmp/creeperpackinstaller
COPY downloadpack.sh .
COPY cleanup.sh .
COPY setup.sh .
RUN chmod +x downloadpack.sh cleanup.sh setup.sh

# Default launch arguments

ENV MAXMEMORY="4G"
ENV MINMEMORY="3072M"

ENTRYPOINT [ "bash", "./setup.sh" ]